GET http://127.0.0.1:3000/user-api/users

###
post http://127.0.0.1:3000/user-api/users
Content-Type: application/json

{
    "id":100,
    "name":"lavanya",
    "age":19
}


###
put http://127.0.0.1:3000/user-api/users/100
Content-Type: application/json

{
    "id":200,
    "name":"Lakshmi",
    "age":25

}

//read user by id
###
Get http://localhost:3000/user-api/users/100

###
DELETE  http://127.0.0.1:3000/user-api/users/100


###
Get http://localhost:3000/product-api/products

###
post http://localhost:3000/product-api/products
Content-Type: application/json

{
    "productId":12345,
    "name":"mobile",
    "price":25000,
    "brand":"samsaung"

}

###
PUT http://localhost:3000/product-api/products/12345
Content-Type: application/json

{
    "productId":67890,
    "name":"laptop",
    "price":45000,
    "brand":"hp"
}

//read product by id
###
Get http://localhost:3000/product-api/products/12345

###
DELETE  http://localhost:3000/product-api/products/12345
