POST http://localhost:4000/product-api/products
Content-Type: application/json

{
    "productname":"laptop",
    "price":60000,
    "brand":"hp"
}

###create user
POST http://localhost:4000/user-api/users
Content-Type: application/json          

{
    "name":"Lakshmi",
    "email":"Lakshmi@gmail.com",
    "password":"Lakshmi",
    "cart":[]
}


### req to add product to cart
PUT  http://localhost:4000/user-api/user-cart/user-id/69819782bdf76fb20017347b/product-id/6981986bbdf76fb20017348c

//findOne({email:req.body.email})
//findById(objId)
###
GET http://localhost:4000/user-api/users/69819782bdf76fb20017347b