### user register
POST http://localhost:4000/user-api/users
Content-Type:application/json

{
    "firstName":"Lakshmi",
    "lastName":"user",
    "email":"Laxmi@gmail.com",
    "password":"Lakshmi@123",
    "profileImageUrl":"https://example.com/avatars/author.png"
}

### author register
POST http://localhost:4000/author-api/author
Content-Type:application/json

{
    "firstName":"Lavanya",
    "lastName":"author",
    "email":"Lav@gmail.com",
    "password":"Lavanya@123",
    "profileImageUrl":"https://exampleone.com/avatars/author.png"
}
###
POST http://localhost:4000/author-api/author
Content-Type:application/json

{
    "firstName":"sunitha",
    "lastName":"author",
    "email":"sun@gmail.com",
    "password":"sun@123",
    "profileImageUrl":"https://exampleone.com/avatars/author.png"
}

### user login
POST http://localhost:4000/common-api/login
Content-Type: application/json 

{
    "email":"Laxmi@gmail.com",
    "password":"Lakshmi@123"
    
}

### Author login
POST http://localhost:4000/common-api/login
Content-Type: application/json 

{
    "email":"Lav@gmail.com",
    "password":"Lavanya@123"
    
}

### create article(author)
POST http://localhost:4000/author-api/articles
Content-Type: application/json

{
    "author":"69b65a787dc6fe108cd2fa2b",
    "title":"sample article",
    "category":"programming",
    "content":"this is a sample article content"
}

### create article(author)
POST http://localhost:4000/author-api/articles
Content-Type: application/json

{
    "author":"69b65a787dc6fe108cd2fa2b",
    "title":"article",
    "category":"coding",
    "content":"this is a sample article content"
}

###read articles of author
GET http://localhost:4000/author-api/articles/69b65a787dc6fe108cd2fa2b

### update article(author)
PUT http://localhost:4000/author-api/articles
Content-Type: application/json

{
    "author":"69b65a787dc6fe108cd2fa2b",
    "articleId":"69b65a9b7dc6fe108cd2fa32",
    "title":"sample article2",
    "category":"programming2",
    "content":"this is a sample article2 content"
}

###delect the article
PATCH http://localhost:4000/author-api/articles/69b65a9b7dc6fe108cd2fa32/status
Content-Type: application/json

{ "isArticleActive": true }


###logout
GET  http://localhost:4000/common-api/logout

###read articles of user
GET http://localhost:4000/user-api/articles

### post comment for article
PUT http://localhost:4000/user-api/articles
Content-Type: application/json

{
    "user":"69b65a6f7dc6fe108cd2fa29",
    "articleId":"69b65a9b7dc6fe108cd2fa32",
    "comment":"This article is more meaningful and useful to everyone"
}



### test req
Get http://localhost:4000/test

### block inactive users
PUT  http://localhost:4000/admin-api/users/69b65a6f7dc6fe108cd2fa29

###unblock 
PUT  http://localhost:4000/admin-api/users/unblock/69b65a6f7dc6fe108cd2fa29


###change password
PUT http://localhost:4000/common-api/change-password
Content-Type: application/json

{
    "email":"Laxmi@gmail.com",
    "currentPassword":"Lakshmi@123",
    "newPassword":"Lak@123"
}